project_id = "wxafugdkvvcymluycngf"

[functions.fetch-fpl-data]
verify_jwt = false

[functions.generate-predictions]
verify_jwt = false

[functions.analyze-user-team]
verify_jwt = false

[functions.update-actual-results]
verify_jwt = false
